server:
  port: 8080
 
eureka:
  client:
#    register-with-eureka: true
#    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
spring:
  application:
    name: 'gateway'
#  cloud:
#    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:8080"
#            allowedHeaders: "*"
#            allowedMethods:
#            - GET
#            - POST
